### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by xmha97** [yasanglass/tehro-android#14]
سلام، لطفاً به برنامه light theme رو هم اضافه کنید.
برا گوشی‌هایی که LCDشون AMOLED نیست، سخته که بخوای تو آفتاب با یه برنامه‌ی light کار کنی.

**Comment by yasandev** [comment]
تهرو هم حالت دارک هم لایت داره که نسبت به تنظیمات دستگاه استفاده میشند. 

![1](https://user-images.githubusercontent.com/41836211/153554082-839fea10-e0be-4f26-b0d3-bc582ad40471.png)
ت

**Comment by xmha97** [comment]
بله، ممنون از شما
